MENU_PREFIX = 'MENU'
SUBSCRIBE_CALLBACK = f'{MENU_PREFIX}_SUBSCRIBE'
UNSUBSCRIBE_CALLBACK = f'{MENU_PREFIX}_UNSUBSCRIBE'
SETTINGS_CALLBACK = f'{MENU_PREFIX}_SETTINGS'
HELP_CALLBACK = f'{MENU_PREFIX}_HELP'

SETTINGS_PREFIX = 'SETTINGS'
LANGUAGE_CALLBACK = f'{SETTINGS_PREFIX}_LANGUAGE'
TIMEZONE_CALLBACK = f'{SETTINGS_PREFIX}_TZ'

LANGUAGE_PREFIX = 'LANG'
HEBREW_CALLBACK = f'{LANGUAGE_PREFIX}_HE_IL'
ENGLISH_CALLBACK = f'{LANGUAGE_PREFIX}_EN_US'

VENUE_PREFIX = 'VENUE'

SUBSCRIBE_POSTFIX = 'SUBSCRIBE'
UNSUBSCRIBE_POSTFIX = 'UNSUBSCRIBE'
